# Generated by Django 5.1.5 on 2025-11-27 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'user_',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(db_column='date_')),
                ('description', models.CharField(db_column='Description', max_length=500)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(db_column='id_1', on_delete=django.db.models.deletion.CASCADE, to='paysible.bankuser')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('account_id_val', models.IntegerField(db_column='account_id')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('account', models.ForeignKey(db_column='id_1', on_delete=django.db.models.deletion.CASCADE, to='paysible.account')),
                ('transaction', models.ForeignKey(db_column='id_transaction', on_delete=django.db.models.deletion.CASCADE, to='paysible.transaction')),
            ],
            options={
                'db_table': 'transaction_entries',
            },
        ),
    ]
